[platformio]
default_envs = T5-ePaper-S3

[env:T5-ePaper-S3]
platform = espressif32@6.12.0
board = T5-ePaper-S3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLILYGO_T5_EPD47_S3
    -DPNG_MAX_BUFFERED_PIXELS=8192
lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#50224221fb81a8fcf9068532374b775af84a38d4
    bblanchon/ArduinoJson@7.4.2
    bitbank2/PNGdec@1.1.6

[env:usb-debug]
extends = env:T5-ePaper-S3
build_flags =
    ${env:T5-ePaper-S3.build_flags}
    -DGERTY_USB_DEBUG=1
