[platformio]
default_envs = T5-ePaper-S3

[env]
platform = espressif32@6.12.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DPNG_MAX_BUFFERED_PIXELS=8192
lib_deps =
    bblanchon/ArduinoJson@7.4.2
    bitbank2/PNGdec@1.1.6

[env:T5-ePaper-S3]
board = T5-ePaper-S3
build_flags =
    ${env.build_flags}
    -DLILYGO_T5_EPD47_S3
lib_deps =
    ${env.lib_deps}
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#50224221fb81a8fcf9068532374b775af84a38d4

[env:guition-JC3248W535]
board = JC3248W535
build_flags =
    ${env.build_flags}
    -DGERTY_GUITION=1
lib_deps =
    ${env.lib_deps}
    moononournation/GFX Library for Arduino@1.4.7

[env:guition-JC4827W543]
board = JC4827W543
build_flags =
    ${env.build_flags}
    -DGERTY_GUITION=1
    -DGERTY_JC4827W543=1
lib_deps =
    ${env.lib_deps}
    moononournation/GFX Library for Arduino@1.4.7
