"""Split the supplied artwork and build PNGs plus flash-resident monochrome data.

Requires ImageMagick (`magick`). Run from any directory; no generated artwork.
"""
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/expressions"
NAMES = "happy thinking excited sleeping waking focused curious confused sad alarmed offline celebrating updating listening mischievous".split()
SIZES = [(240, 240), (480, 272), (480, 320), (800, 480), (960, 540)]
COLS = [(20, 285), (325, 280), (630, 275), (905, 325), (1230, 286)]
ROWS = [(110, 220), (400, 218), (700, 190)]

def magick(*args):
    return subprocess.check_output(["magick", *map(str, args)])

header = ["// Generated by tools/prepare_expressions.py; black pixels are 1.",
          "#pragma once", "#include <stdint.h>", "namespace Expressions {",
          "enum class Face { " + ", ".join(n.title() for n in NAMES) + " };",
          "constexpr int WIDTH = 320, HEIGHT = 240;",
          "static const uint8_t BITMAPS[][9600] = {"]
lcd_data = {size: [] for size in SIZES[:3]}
for i, name in enumerate(NAMES):
    x, w = COLS[i % 5]
    y, h = ROWS[i // 5]
    if i < 3:
        y, h = 160, 170  # Exclude the poster subtitle above the first three faces.
    target = OUT / f"{name}.png"
    magick(OUT / "source/expressions.png", "-crop", f"{w}x{h}+{x}+{y}",
           "+repage", "-colorspace", "Gray", "-threshold", "55%", "-trim",
           "+repage", "-resize", "280x200", "-gravity", "center", "-background",
           "white", "-extent", "320x240", "-threshold", "50%", target)
    smooth_folder = OUT / "lcd"
    smooth_folder.mkdir(exist_ok=True)
    smooth_target = smooth_folder / f"{name}.png"
    # Keep the source edge coverage instead of smoothing an already thresholded
    # bitmap. Levels clean the poster's near-white background and near-black ink.
    magick(OUT / "source/expressions.png", "-crop", f"{w}x{h}+{x}+{y}",
           "+repage", "-colorspace", "Gray", "-level", "10%,90%", "-trim",
           "+repage", "-filter", "Lanczos", "-resize", "280x200", "-gravity",
           "center", "-background", "white", "-extent", "320x240", "-depth", "8",
           smooth_target)
    # Use 8-bit grayscale for an unambiguous header-free data stream.
    pixels = magick(target, "-depth", "8", "GRAY:-")
    packed = bytes(sum((pixels[p + bit] < 128) << (7 - bit) for bit in range(8))
                   for p in range(0, len(pixels), 8))
    assert len(packed) == 9600
    header.append("  { // " + name)
    header.extend("    " + ",".join(f"0x{b:02x}" for b in packed[p:p+32]) + ","
                  for p in range(0, len(packed), 32))
    header.append("  },")
    for width, height in SIZES:
        folder = OUT / f"{width}x{height}"
        folder.mkdir(exist_ok=True)
        lcd = (width, height) in lcd_data
        # Preserve gray edge coverage for LCDs; e-paper remains strictly binary.
        magick(smooth_target if lcd else target,
               *(["-filter", "Lanczos"] if lcd else []), "-resize", f"{width}x{height}", "-gravity", "center",
               "-background", "white", "-extent", f"{width}x{height}",
               *(["-depth", "8"] if lcd else ["-threshold", "50%"]),
               folder / f"{name}.png")
        if lcd:
            pixels = magick(folder / f"{name}.png", "-depth", "8", "GRAY:-")
            # RGB565 produces the same colour for each group of four gray
            # values. Merge those before encoding without changing display pixels.
            pixels = bytes(255 if value >= 252 else value & 252 for value in pixels)
            # Row-local runs: 8-bit length minus one followed by gray.
            # This keeps the smooth native-resolution faces small in flash.
            runs = bytearray()
            for row in range(height):
                start = row * width
                end = start + width
                while start < end:
                    stop = start + 1
                    while stop < end and stop - start < 256 and pixels[stop] == pixels[start]:
                        stop += 1
                    length = stop - start
                    runs.extend((length - 1, pixels[start]))
                    start = stop
            lcd_data[(width, height)].append(runs)
header.extend(["};", "} // namespace Expressions", ""])
(ROOT / "include/expression_bitmaps.h").write_text("\n".join(header))
for (width, height), faces in lcd_data.items():
    lines = ["// Generated by tools/prepare_expressions.py. Native antialiased LCD faces.",
             "#pragma once", "#include <stdint.h>", "namespace LcdExpressions {",
             f"constexpr int WIDTH = {width}, HEIGHT = {height};"]
    for name, runs in zip(NAMES, faces):
        lines.append(f"static const uint8_t {name}[] = {{")
        lines.extend("  " + ",".join(str(b) for b in runs[p:p+36]) + ","
                     for p in range(0, len(runs), 36))
        lines.append("};")
    lines.extend(["static const uint8_t *const FACES[] = {" + ",".join(NAMES) + "};", "}"])
    (ROOT / f"include/expression_lcd_{width}x{height}.h").write_text("\n".join(lines) + "\n")
magick("montage", *(OUT / f"{name}.png" for name in NAMES),
       "-tile", "5x3", "-geometry", "240x180+4+4", OUT / "preview.png")
